let tagsList = [{
        value: '0',
        label: '穿无尘服'
      }, {
        value: '1',
        label: '包吃'
      }, {
        value: '2',
        label: '包住'
      }, {
        value: '3',
        label: '餐补'
      }, {
        value: '4',
        label: '房补'
      }, {
        value: '5',
        label: '五险'
      }, {
        value: '6',
        label: '五险一金'
      }, {
        value: '7',
        label: '交通补助'
      }, {
        value: '8',
        label: '话补'
      }, {
        value: '9',
        label: '周末双休'
      }, {
        value: '10',
        label: '年底双薪'
      }, {
        value: '11',
        label: '长白班'
      }, {
        value: '12',
        label: '免费商业险'
      }, {
        value: '13',
        label: '站姿上班'
      }, {
        value: '14',
        label: '加班多'
      }, {
        value: '15',
        label: '妹子多'
      }, {
        value: '16',
        label: '周围热闹'
      }, {
        value: '17',
        label: '吃住好'
      }, {
        value: '18',
        label: '年龄要求低'
      }, {
        value: '19',
        label: '日多薪'
      }]

export default tagsList
